$ANSIBLE_VAULT;1.1;AES256
31336165663632323636343239643631643430373164633039343764646265656232656233623938
6638346533643036333732303831383963336339613665370a653137663662333435393130643538
39636464373035336236646166313939386337666130353637623737643565396334326237616661
3332303238373134310a363336383262623664336638626330316635353331613430313065313036
36316235353164613133333461626463613037323134326131396539306532663664323335343435
64666234333138383139383164336530623363346639393039313430323939383464333435643061
373132613765353934613536373932633966
